
################################################################################
#  Author: salvo ventura
#    Date: Oct 2007
# Purpose: installation script for PANTESTING
#          This should be run after the tar ball containing all of the PANTESTING
#          data (scripts/binaries/tools) has been uncompressed in the destination
#          location.
#          This will take care of:
#          - setting environment variables
#          - update PATH
#
# SHOULD NOT BE RUN MORE THAN ONCE
################################################################################
LOG='install.log'

# get local information
CURPATH=`pwd`
CURUSER=`whoami`
CUROS=`uname`
CURSHELL=`echo $SHELL`

echo "`date`, PANTESTING INSTALLATION SCRIPT" >> $LOG
echo "===============================================================================" >> $LOG
echo "PATH=$CURPATH   USER=$CURUSER   OS=$CUROS   SHELL=$CURSHELL" >> $LOG

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# check for lock file: if there, means install was already run: don't allow to rerun
if [ -e ".install_done" ]; then
  msg="Installation was already run: cannot re-run"
  echo $msg
  echo $msg >> $LOG
  exit 1;
fi;

# if not bash, exit
case `basename $SHELL` in
bash)
  msg="Found $SHELL"
  echo $msg >> $LOG
  ;;
*)
  msg="Default shell is $SHELL. Sorry, currently only bash is supported. Exiting."
  echo $msg
  echo $msg >> $LOG
  exit 1;
  ;;
esac

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# generate aliases
# export PANTESTING and PAN_CONTENT
# Update PATH
# create symbolic link into /usr/lib
# 
# Put all this stuff into a fresh .bashrc_pantesting
#
PANPROFILE='.bashrc_pantesting'
echo "#`date` - generated by $0" > $PANPROFILE
echo "" >> $PANPROFILE
echo "# Environment variables" >> $PANPROFILE
echo "export PANTESTING=$CURPATH" >> $PANPROFILE
echo "export PANTESTING=$CURPATH" >> $PANPROFILE
echo "export PANTESTINGVERSION=`cat VERSION`" >> $PANPROFILE
echo "export PATH=\$PATH:\$PANTESTING/bin:\$PATH:\$PANTESTING/utils" >> $PANPROFILE
echo "" >> $PANPROFILE
echo "# Aliases" >> $PANPROFILE
echo "set vi='vim'" >> $PANPROFILE
echo "set sec2time='sec2time.sh'" >> $PANPROFILE

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
# Add line into .bashrc to source it
PROFILE=`echo ~/.bashrc`
echo "" >> $PROFILE
echo "#`date` - generated by $0" >> $PROFILE
echo "#========================================================" >> $PROFILE
echo "source ${CURPATH}/${PANPROFILE}" >> $PROFILE
echo "" >> $PROFILE

################################################################################
#
echo "`date`, PANTESTING INSTALLATION DONE" >> $LOG
echo "" >> $LOG

# create 'lock' file
touch .install_done
echo "Done!"
exit 0